name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.68.2, stable, nightly]
    steps:
    - uses: actions/checkout@v3
    - run: rustup install ${{ matrix.rust }}
    - run: cargo +${{ matrix.rust }} build --verbose
    - run: cargo +${{ matrix.rust }} test --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup component add clippy
    - run: cargo clippy
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup component add rustfmt
    - run: cargo fmt -- --check
