name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.71.1, stable, nightly]
    steps:
    - uses: actions/checkout@v3
    - run: rustup install ${{ matrix.rust }}
    - run: cargo +${{ matrix.rust }} build --workspace --verbose
    - run: |
        cargo +${{ matrix.rust }} test --workspace --verbose \
            -- --skip utils::tests::kms # Requires AWS creds
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup component add clippy
    - run: cargo clippy --workspace
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup component add rustfmt
    - run: cargo fmt --all --check
